version: '3.8'

services:
  app:
    build: .
    container_name: laravel-dons-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - dons-network
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    container_name: laravel-dons-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dons-network
    depends_on:
      - app

  database:
    image: postgres:15
    container_name: laravel-dons-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: Dons
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9zctibtytwmv640w
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dons-network

networks:
  dons-network:
    driver: bridge

volumes:
  postgres_data: